FROM python:3.5.1-onbuild
CMD [ "python", "./main.py" ]

# docker build -t python-wshell .
# docker run --rm --name python-wshell main.py

# docker run --rm -v "$PWD"/cache/python-wshell:/usr/src/myapp -w /usr/src/myapp python-wshell python main.py
